version: '3.8'

services:


  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080
    environment:
      MAILDEV_SMTP_PORT: 25

  keycloak-nest:
    image: quay.io/keycloak/keycloak:24.0.3
    command: ['start-dev', '--verbose', '--import-realm']
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import
      KEYCLOAK_PROFILE_FEATURE_UPLOAD_SCRIPTS: enabled
    volumes:
      - ./keycloak/data/import:/opt/keycloak/data/import

  # app:
  #   build: .
  #   command: npm run start:dev
  #   volumes:
  #     - .:/usr/src/app
  #     - node_modules:/usr/src/app/node_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - keycloak
  #   environment:
  #     NODE_ENV: development
  #     KEYCLOAK_BASE_URL: 'http://keycloak:8080'
  #     KEYCLOAK_REALM: ${KEYCLOAK_REALM}
  #     KEYCLOAK_REALM_RSA_PUBLIC_KEY: ${KEYCLOAK_REALM_RSA_PUBLIC_KEY}
  #     KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
  #     KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}

volumes:
  node_modules:
