POST http://localhost:8080/realms/auth-nestjs/protocol/openid-connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

&client_id=nest-client
&client_secret=XSwT7oB5fcNIhxb3NPI0c2XV4FvcTJze
&username=foo
&password=123
&grant_type=password

###
GET http://localhost:3000/auth/login

###
POST http://localhost:3000/auth/sing-in HTTP/1.1
content-type: application/json

{
	"username":"foo",
	"password":"123"
}
###


"solicitudId": "HllClBAFk6-20240611",
    "eventId": "e88209ea-2931-3634-6f3e-db2fdcee1fa6"


